timezone: "Asia/Tokyo"

anni:
  nexus:
    health: 100
    material: END_STONE

  teams:
    red:
      id: "red"
      display: "赤"
      prefix: "&7[&cR&7] &r"
      team-color: "c"

      big-logo:
        - "&7⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛"
        - "&7⬛⬛&t⬛⬛⬛⬛⬛&7⬛⬛⬛"
        - "&7⬛⬛&t⬛&7⬛⬛⬛⬛&t⬛&7⬛⬛"
        - "&7⬛⬛&t⬛&7⬛⬛⬛⬛&t⬛&7⬛⬛"
        - "&7⬛⬛&t⬛⬛⬛⬛⬛&7⬛⬛⬛"
        - "&7⬛⬛&t⬛&7⬛&t⬛&7⬛⬛⬛⬛⬛"
        - "&7⬛⬛&t⬛&7⬛⬛&t⬛&7⬛⬛⬛⬛"
        - "&7⬛⬛&t⬛&7⬛⬛⬛&t⬛&7⬛⬛⬛"
        - "&7⬛⬛&t⬛&7⬛⬛⬛⬛&t⬛&7⬛⬛"
        - "&7⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛"
    blue:
      id: "blue"
      display: "青"
      prefix: "&7[&9B&7] &r"
      team-color: "9"

      big-logo:
        - "&7⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛"
        - "&7⬛⬛&t⬛⬛⬛⬛⬛&7⬛⬛⬛"
        - "&7⬛⬛&t⬛&7⬛⬛⬛⬛&t⬛&7⬛⬛"
        - "&7⬛⬛&t⬛&7⬛⬛⬛⬛&t⬛&7⬛⬛"
        - "&7⬛⬛&t⬛⬛⬛⬛⬛&7⬛⬛⬛"
        - "&7⬛⬛&t⬛&7⬛⬛⬛⬛&t⬛&7⬛⬛"
        - "&7⬛⬛&t⬛&7⬛⬛⬛⬛&t⬛&7⬛⬛"
        - "&7⬛⬛&t⬛&7⬛⬛⬛⬛&t⬛&7⬛⬛"
        - "&7⬛⬛&t⬛⬛⬛⬛⬛&7⬛⬛⬛"
        - "&7⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛"
    yellow:
      id: "yellow"
      display: "黄"
      prefix: "&7[&eY&7] &r"
      team-color: "e"

      big-logo:
        - "&7⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛"
        - "&7⬛⬛&t⬛&7⬛⬛⬛⬛&t⬛&7⬛⬛"
        - "&7⬛⬛&t⬛&7⬛⬛⬛⬛&t⬛&7⬛⬛"
        - "&7⬛⬛&t⬛&7⬛⬛⬛⬛&t⬛&7⬛⬛"
        - "&7⬛⬛⬛&t⬛&7⬛⬛&t⬛&7⬛⬛⬛"
        - "&7⬛⬛⬛⬛&t⬛⬛&7⬛⬛⬛⬛"
        - "&7⬛⬛⬛⬛&t⬛⬛&7⬛⬛⬛⬛"
        - "&7⬛⬛⬛⬛&t⬛⬛&7⬛⬛⬛⬛"
        - "&7⬛⬛⬛⬛&t⬛⬛&7⬛⬛⬛⬛"
        - "&7⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛"
    green:
      id: "green"
      display: "緑"
      prefix: "&7[&9G&7] &r"
      team-color: "a"

      big-logo:
        - "&7⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛"
        - "&7⬛⬛⬛&t⬛⬛⬛⬛&7⬛⬛⬛"
        - "&7⬛⬛&t⬛&7⬛⬛⬛⬛&t⬛&7⬛⬛"
        - "&7⬛⬛&t⬛&7⬛⬛⬛⬛⬛⬛⬛"
        - "&7⬛⬛&t⬛&7⬛⬛&t⬛⬛⬛&7⬛⬛"
        - "&7⬛⬛&t⬛⬛⬛⬛⬛⬛&7⬛⬛"
        - "&7⬛⬛&t⬛⬛⬛⬛⬛⬛&7⬛⬛"
        - "&7⬛⬛&t⬛⬛⬛⬛⬛⬛&7⬛⬛"
        - "&7⬛⬛⬛&t⬛⬛⬛⬛⬛&7⬛⬛"
        - "&7⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛"

# DO NOT edit
config-version: 0