name: "NANNI"
version: '0.8-alpha'
author: "Taitaitatata"
description: "NANNIはNekozouneko Serverのアナイアレーションを管理・実行するプラグインです"

main: com.nekozouneko.anni.ANNIPlugin
api-version: 1.16
loadbefore: ["PlaceholderAPI","Vault", "Votifier", "WorldEdit", "WorldGuard"]
depend: ["PlaceholderAPI","Vault", "Votifier", "WorldEdit", "WorldGuard"]

commands:
  nanni:
    aliases: ["anni"]
    permission: nanni.command.nanni
    usage: '/<command>'

  nanni-admin:
    aliases: ["anni-admin", "nannim", "annim"]
    permission: nanni.command.admin
    usage: |
      /<command> map add <world> <displayName>
      /<command> map edit <world> name <displayName>
      /<command> map edit <world> setblock <type>
      /<command> map edit <world> rule <TvT|TvTvTvT>
      /<command> map edit <world> nexus <team>
      /<command> map list
      /<command> map remove <world>

  # -----
  points:
    aliases: ["p"]
    description: "現在所持しているポイントを取得します"
    usage: "/<command> [target]"
    permission: nanni.command.points

default-permission: true

permissions:
  nanni:
    children:
      - nanni.command

  nanni.command:
    children:
      - nanni.command.admin
      - nanni.command.nanni
      - nanni.command.points
      - nanni.command.points.other

  nanni.command.admin:
    default: op

  nanni.command.nanni:
    default: true

  nanni.command.points:
    default: true

  nanni.command.points.other:
    default: op