name: "Build NANNI Plugin"

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      java: ["8", "16", "17"]

    name: Build with ${{ matrix.java }}

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Set up Java ${{ matrix.java }}"
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: "Check version"
        run: java -version && mvn --version

      - name: "Build"
        run: mvn clean install

      - name: "Upload artifacts (${{ matrix.java }})"
        uses: actions/upload-artifact@v3.1.1
        with:
          name: "Target Directory (${{ matrix.java }})"
          path:
            ./*/target/*